language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.8"
  - "pypy"
  - "pypy3"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
# - "pip install -r requirements.txt --use-mirrors"
  - "pip install coverage"
  - "pip install coveralls"

# command to run tests, e.g. python setup.py test
script:
  "coverage run -m unittest discover -s . -p '*_unit_test.py'"

after_success:
  coveralls
