language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy3"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
# - "pip install -r requirements.txt --use-mirrors"
  - "pip install coverage"
  - "pip install coveralls"

# command to run tests, e.g. python setup.py test
script:
  "coverage run -m unittest discover -s . -p 'tests/test*.py'"
  "pytest -s --cov=nba_scraper 'tests/test*.py'"

env:
    - CODECOV_TOKEN='cec7e21c-30fb-4155-b026-fa239c9ccb5e' #IF ONLY YOU HAVE A PRIVATE REPOSITORY

after_success:
    - codecov
    - coveralls
